# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2
maxReplicaCount: 4

image:
  repository: quay.io/hmpps/offender-assessment-events
  tag: latest
  port: 8080

cronjob:
  enabled: false

deployment:
  resources:
    requests:
      cpu: 10m
      memory: 640Mi
    limits:
      cpu: 2000m
      memory: 1280Mi

env:
  JAVA_OPTS: "-Xmx512m"
  LAST_ACCESSED_EVENT_DIR: /tmp
