CREATE TABLE EVENT_LOG (
	EVENT_LOG_PK NUMBER,
	EVENT_TABLE VARCHAR2(40),
	EVENT_INSTANCE NUMBER,
	EVENT_DATE DATE,
	OASYS_USER_CODE VARCHAR2(100),
	EVENT_TYPE_CODE VARCHAR2(100),
	EVENT_TEXT VARCHAR2(4000),
	CT_AREA_EST_CODE VARCHAR2(100),
	OFFENDER_PK NUMBER,
	EVENT_LEVEL NUMBER,
	IP_ADDRESS VARCHAR2(100),
	CHECKSUM VARCHAR2(4000),
	CONSTRAINT EVENT_LOG_PK PRIMARY KEY (EVENT_LOG_PK),
	CONSTRAINT SYS_C007656 CHECK (EVENT_LOG_PK),
	CONSTRAINT SYS_C007657 CHECK (OASYS_USER_CODE),
	CONSTRAINT SYS_C007658 CHECK (EVENT_TYPE_CODE),
	CONSTRAINT SYS_C007659 CHECK (CT_AREA_EST_CODE)
-- 	CONSTRAINT CAE_ELO FOREIGN KEY (CT_AREA_EST_CODE) REFERENCES CT_AREA_EST(CT_AREA_EST_CODE),
-- 	CONSTRAINT ETY_ELO FOREIGN KEY (EVENT_TYPE_CODE) REFERENCES EVENT_TYPE(EVENT_TYPE_CODE),
-- 	CONSTRAINT OUS_ELO FOREIGN KEY (OASYS_USER_CODE) REFERENCES OASYS_USER(OASYS_USER_CODE)
);

CREATE INDEX EVENT_LOG_EI_HP_IDX ON EVENT_LOG (EVENT_INSTANCE);
CREATE INDEX EVENT_LOG_FKX1 ON EVENT_LOG (OASYS_USER_CODE);
CREATE INDEX EVENT_LOG_FKX2 ON EVENT_LOG (CT_AREA_EST_CODE);
CREATE INDEX EVENT_LOG_FKX3 ON EVENT_LOG (EVENT_TYPE_CODE);
CREATE INDEX EVENT_LOG_FKX4 ON EVENT_LOG (OFFENDER_PK);
CREATE UNIQUE INDEX EVENT_LOG_PK ON EVENT_LOG (EVENT_LOG_PK);